[build]
  publish="./dist"
  base = "."


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "sameorigin"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
